import {
  version as wasmVersion,
  add as wasmAdd,
  encode_terrarium,
  encode_mapbox,
  rgb_to_webp,
  rgb_to_png,
  encode_quantized_mesh,
} from "./wasm/terrain-codec/terrain_codec.js";
import { openCog } from "./cog.js";
import { readTileFromImage, tileToLonLatBounds } from "./tile.js";
import { readTileSamples, type DataType } from "./blend.js";
import {
  DEFAULT_TILESET,
  TILESETS,
  resolveTileset,
  resolveTilesetVersion,
  type Tileset,
} from "./tilesets.js";
import { cachedTile, bodyEtag, matchesIfNoneMatch } from "./cache.js";
import { runCleanup } from "./cleanup.js";
import {
  MESH_GRID_SIZE,
  buildWaterMask,
  fullAvailability,
  geodeticTileBounds,
  sampleGrid,
  type SampleDataType,
} from "./cesium.js";
import { ProtomapsWaterMask } from "./water.js";
import { currentPmtilesDate, pmtilesUrlForDate } from "./protomaps.js";

// Memoize one provider per resolved URL so the PMTiles header fetched at
// construction time is reused across requests within a worker instance.
const waterProviders = new Map<string, ProtomapsWaterMask>();
function getWaterProvider(url: string): ProtomapsWaterMask {
  let p = waterProviders.get(url);
  if (!p) {
    p = new ProtomapsWaterMask(url);
    waterProviders.set(url, p);
  }
  return p;
}

/** TTL for the per-tile Mapterhorn freshness probe — see `cache.ts`. */
const DEM_FRESHNESS_TTL_MS = 6 * 60 * 60 * 1000;

/**
 * Build a per-tile freshness probe for the underlying DEM, or `undefined`
 * when the request doesn't read the DEM at all (`data_type=geoid`) or the
 * DEM source doesn't expose a freshness signal. The probe is what lets
 * `cachedTile` invalidate stale L2 entries surgically when Mapterhorn
 * rebuilds a region.
 */
function demFreshness(
  tileset: Tileset,
  dataType: string,
  z: number,
  x: number,
  y: number,
): { check: () => Promise<Date | null>; ttlMs: number } | undefined {
  if (dataType === "geoid") return undefined;
  const probe = tileset.dem.freshness;
  if (!probe) return undefined;
  return {
    check: () => probe.call(tileset.dem, z, x, y),
    ttlMs: DEM_FRESHNESS_TTL_MS,
  };
}

/**
 * Resolve a tileset's watermask source down to the concrete URL and version
 * we'll fetch/cache against. Returns null when the tileset has no watermask
 * configured.
 */
async function resolveWatermask(
  tileset: Tileset,
): Promise<{ url: string; version: string; provider: ProtomapsWaterMask } | null> {
  if (!tileset.watermask) return null;
  if (tileset.watermask.kind === "protomaps-daily") {
    const date = await currentPmtilesDate();
    const url = pmtilesUrlForDate(date);
    return { url, version: `protomaps-${date}`, provider: getWaterProvider(url) };
  }
  return null;
}

// Route patterns. Tileset name comes first when present; the no-tileset
// form resolves to DEFAULT_TILESET.
const TILE_WITH_TILESET = /^\/([a-z0-9-]+)\/(terrarium|mapbox)\/(geoid|elevation|ellipsoid)\/(\d+)\/(\d+)\/(\d+)\.(webp|png)$/;
const TILE_DEFAULT = /^\/(terrarium|mapbox)\/(geoid|elevation|ellipsoid)\/(\d+)\/(\d+)\/(\d+)\.(webp|png)$/;
const TILEJSON_WITH_TILESET = /^\/([a-z0-9-]+)\/(terrarium|mapbox)\/(geoid|elevation|ellipsoid)\/tilejson\.json$/;
const TILEJSON_DEFAULT = /^\/(terrarium|mapbox)\/(geoid|elevation|ellipsoid)\/tilejson\.json$/;
const MESH_TILE_WITH_TILESET = /^\/([a-z0-9-]+)\/cesium-mesh\/(geoid|elevation|ellipsoid)\/(\d+)\/(\d+)\/(\d+)\.terrain$/;
const MESH_TILE_DEFAULT = /^\/cesium-mesh\/(geoid|elevation|ellipsoid)\/(\d+)\/(\d+)\/(\d+)\.terrain$/;
const MESH_LAYER_WITH_TILESET = /^\/([a-z0-9-]+)\/cesium-mesh\/(geoid|elevation|ellipsoid)\/layer\.json$/;
const MESH_LAYER_DEFAULT = /^\/cesium-mesh\/(geoid|elevation|ellipsoid)\/layer\.json$/;

type Encoding = "terrarium" | "mapbox";
type Format = "webp" | "png";

// `Env` itself is generated by `wrangler types` from wrangler.toml
// (see worker-configuration.d.ts). No augmentation needed today.

export default {
  async fetch(req: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(req.url);

    try {
      // Tile requests (with or without explicit tileset).
      let m = TILE_WITH_TILESET.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(m[1]);
        if (!tileset) return notFound(`unknown tileset: ${m[1]}`);
        return await serveTile(req, ctx, tileset, m[2] as Encoding, m[3] as DataType, Number(m[4]), Number(m[5]), Number(m[6]), m[7] as Format, env);
      }
      m = TILE_DEFAULT.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(undefined);
        if (!tileset) return notFound("default tileset not configured");
        return await serveTile(req, ctx, tileset, m[1] as Encoding, m[2] as DataType, Number(m[3]), Number(m[4]), Number(m[5]), m[6] as Format, env);
      }

      // TileJSON metadata.
      m = TILEJSON_WITH_TILESET.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(m[1]);
        if (!tileset) return notFound(`unknown tileset: ${m[1]}`);
        return await tilejson(req, tileset, m[2] as Encoding, m[3] as DataType);
      }
      m = TILEJSON_DEFAULT.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(undefined);
        if (!tileset) return notFound("default tileset not configured");
        return await tilejson(req, tileset, m[1] as Encoding, m[2] as DataType);
      }

      // Cesium quantized-mesh tile.
      m = MESH_TILE_WITH_TILESET.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(m[1]);
        if (!tileset) return notFound(`unknown tileset: ${m[1]}`);
        return await serveMesh(req, ctx, tileset, m[2] as SampleDataType, Number(m[3]), Number(m[4]), Number(m[5]), url.searchParams, env);
      }
      m = MESH_TILE_DEFAULT.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(undefined);
        if (!tileset) return notFound("default tileset not configured");
        return await serveMesh(req, ctx, tileset, m[1] as SampleDataType, Number(m[2]), Number(m[3]), Number(m[4]), url.searchParams, env);
      }
      // Note: serveMesh also inspects the Accept header for an
      // `extensions=` parameter, which is how CesiumJS itself signals
      // octvertexnormals / watermask preferences.

      // Cesium layer.json metadata.
      m = MESH_LAYER_WITH_TILESET.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(m[1]);
        if (!tileset) return notFound(`unknown tileset: ${m[1]}`);
        return await meshLayerJson(req, tileset, m[2] as SampleDataType);
      }
      m = MESH_LAYER_DEFAULT.exec(url.pathname);
      if (m) {
        const tileset = resolveTileset(undefined);
        if (!tileset) return notFound("default tileset not configured");
        return await meshLayerJson(req, tileset, m[1] as SampleDataType);
      }

      // `/debug/*` endpoints are introspection-only and stay disabled in
      // production; `.dev.vars` flips ENABLE_DEBUG=1 for local use.
      if (url.pathname.startsWith("/debug/") && !debugEnabled(env)) {
        return notFound();
      }

      switch (url.pathname) {
        case "/health":
          return json({ ok: true, environment: env.ENVIRONMENT ?? "unknown" });

        case "/tilesets":
          return await metadataJson(req, {
            default: DEFAULT_TILESET,
            tilesets: Object.values(TILESETS).map(tilesetSummary),
          });

        case "/hello-wasm": {
          const a = Number(url.searchParams.get("a") ?? "1");
          const b = Number(url.searchParams.get("b") ?? "2");
          return json({ codec: wasmVersion(), sum: wasmAdd(a, b) });
        }

        case "/terrarium-sample": {
          const elev = new Float32Array([0, 100, -50, 8848]);
          const rgb = encode_terrarium(elev, 2, 2);
          return new Response(rgb, {
            headers: { "content-type": "application/octet-stream" },
          });
        }

        case "/debug/cog":
          return debugCog(url, env);

        case "/debug/tile":
          return debugTile(url, env);

        case "/debug/dem":
          return debugDem(url);

        case "/debug/ellipsoid":
          return debugSamples(url, env);

        case "/debug/watermask":
          return debugWaterMask(url, env);

        case "/debug/cleanup":
          return debugCleanup(url, env);
      }
    } catch (err) {
      return json(
        { error: String(err instanceof Error ? err.message : err) },
        { status: 500 },
      );
    }

    return notFound();
  },

  // Cron-driven stale L2 cache cleanup. Removes `cache/terrain/{tileset}/v{N}/`
  // prefixes that no longer match a live entry in TILESETS. See `src/cleanup.ts`
  // for the walk + budget logic, and `wrangler.toml` `[triggers]` for the
  // schedule.
  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    console.log("scheduled: cleanup tick", {
      cron: controller.cron,
      scheduledTime: controller.scheduledTime,
    });
    if (!env.R2) {
      console.warn("scheduled: R2 binding missing, skipping cleanup");
      return;
    }
    ctx.waitUntil(
      runCleanup(env.R2, resolveLiveCleanupTilesets()).catch((err) => {
        console.error("scheduled: cleanup failed", err);
      }),
    );
  },
} satisfies ExportedHandler<Env>;

async function serveTile(
  req: Request,
  ctx: ExecutionContext,
  tileset: Tileset,
  encoding: Encoding,
  dataType: DataType,
  z: number,
  x: number,
  y: number,
  format: Format,
  env: Env,
): Promise<Response> {
  return cachedTile(
    req,
    ctx,
    env.R2,
    {
      tileset: tileset.name,
      version: resolveTilesetVersion(tileset),
      encoding,
      dataType,
      z,
      x,
      y,
      format,
      freshness: demFreshness(tileset, dataType, z, x, y),
    },
    async () => {
      const samples = await readTileSamples(tileset, dataType, z, x, y, env);
      const rgb =
        encoding === "terrarium"
          ? encode_terrarium(samples.values, samples.width, samples.height)
          : encode_mapbox(samples.values, samples.width, samples.height);
      const bytes =
        format === "webp"
          ? rgb_to_webp(rgb, samples.width, samples.height)
          : rgb_to_png(rgb, samples.width, samples.height);
      return {
        bytes,
        contentType: format === "webp" ? "image/webp" : "image/png",
      };
    },
    cacheDisabled(env),
  );
}

/** True when the dev `.dev.vars` (or any deploy env) opts out of tile caching. */
function cacheDisabled(env: Env): boolean {
  const v = env.DISABLE_CACHE;
  return v === "1" || v?.toLowerCase() === "true";
}

/** True when `/debug/*` endpoints are opted in (set via `.dev.vars` locally). */
function debugEnabled(env: Env): boolean {
  const v = env.ENABLE_DEBUG;
  return v === "1" || v?.toLowerCase() === "true";
}

async function serveMesh(
  req: Request,
  ctx: ExecutionContext,
  tileset: Tileset,
  dataType: SampleDataType,
  z: number,
  x: number,
  y: number,
  query: URLSearchParams,
  env: Env,
): Promise<Response> {
  // CesiumJS signals which extensions it wants via the Accept header:
  //   Accept: application/vnd.quantized-mesh;extensions=octvertexnormals-watermask, ...
  // (Quantized Mesh GitHub doc). Some clients also append
  // `?extensions=...` to the URL. We honour both, plus simple boolean
  // query params for ad-hoc clients.
  const extensions = new Set<string>([
    ...parseExtensionsFromAccept(req.headers.get("accept")),
    ...(query.get("extensions") ?? "").split("-").map((s) => s.trim().toLowerCase()).filter(Boolean),
  ]);
  const includeNormals = extensions.has("octvertexnormals") || boolParam(query, "normals");
  const includeWaterMask = extensions.has("watermask") || boolParam(query, "watermask");

  // Resolve the watermask source up-front (HEAD-probed, cached) so its
  // version can be folded into the cache key BEFORE the cache lookup
  // happens. A new daily build flips the version and naturally
  // invalidates only watermask-bearing entries.
  const watermask = includeWaterMask ? await resolveWatermask(tileset) : null;

  const variant: string[] = [];
  if (includeNormals) variant.push("n");
  if (includeWaterMask) {
    variant.push(watermask ? `w-${watermask.version}` : "w-fallback");
  }
  const encoding = variant.length ? `cesium-mesh+${variant.join("+")}` : "cesium-mesh";

  return cachedTile(
    req,
    ctx,
    env.R2,
    {
      tileset: tileset.name,
      version: resolveTilesetVersion(tileset),
      encoding,
      dataType,
      z,
      x,
      y,
      format: "terrain",
      fallbackContentType: "application/vnd.quantized-mesh",
      freshness: demFreshness(tileset, dataType, z, x, y),
    },
    async () => {
      const bounds = geodeticTileBounds(z, x, y);

      // Watermask comes from Protomaps when available — that's correct
      // over polders, salt flats, and high-altitude lakes that an
      // elevation threshold gets wrong. The DEM heuristic stays as a
      // fallback so the feature degrades gracefully if PMTiles fetches
      // fail (or have been disabled via env).
      // When normals are requested we need a 1-cell halo around the tile so
      // the mesh encoder can compute DEM-gradient normals that stay
      // continuous across tile boundaries (vs. the per-tile face-normal
      // path, which is visibly discontinuous at seams).
      const haloCells = includeNormals ? 1 : 0;
      const [{ elevations, dem, elevationsWithHalo }, waterFromProtomaps] = await Promise.all([
        sampleGrid(tileset, bounds, MESH_GRID_SIZE, dataType, env, { haloCells }),
        watermask ? watermask.provider.buildMask(bounds).catch(() => null) : Promise.resolve(null),
      ]);

      let waterMaskBytes: Uint8Array;
      if (!includeWaterMask) {
        waterMaskBytes = new Uint8Array(0);
      } else if (waterFromProtomaps) {
        waterMaskBytes = waterFromProtomaps;
      } else if (dem) {
        waterMaskBytes = buildWaterMask(dem, MESH_GRID_SIZE, 0);
      } else {
        waterMaskBytes = new Uint8Array([0]);
      }

      const bytes = encode_quantized_mesh(
        elevations,
        bounds.west,
        bounds.south,
        bounds.east,
        bounds.north,
        meshMaxErrorForZoom(z),
        0, // raw bytes — workerd / Cloudflare handle wire compression
        includeNormals,
        waterMaskBytes,
        elevationsWithHalo ?? new Float64Array(0),
        haloCells,
      );
      return {
        bytes,
        contentType: "application/vnd.quantized-mesh",
      };
    },
    cacheDisabled(env),
  );
}

function boolParam(query: URLSearchParams, key: string): boolean {
  const v = query.get(key);
  return v != null && v !== "0" && v.toLowerCase() !== "false";
}

/**
 * Parse Cesium-style extensions out of an Accept header. The header looks
 * like `application/vnd.quantized-mesh;extensions=octvertexnormals-watermask, ...`
 * — multiple media types separated by commas, each with `;param=value` bits.
 * We only care about `extensions` parameters; the values themselves are
 * dash-separated extension names.
 */
function parseExtensionsFromAccept(accept: string | null): string[] {
  if (!accept) return [];
  const out: string[] = [];
  for (const part of accept.split(",")) {
    for (const param of part.split(";").slice(1)) {
      const [k, v] = param.split("=").map((s) => s.trim());
      if (k?.toLowerCase() === "extensions" && v) {
        for (const ext of v.split("-")) {
          const name = ext.trim().toLowerCase();
          if (name) out.push(name);
        }
      }
    }
  }
  return out;
}

/** Cesium expects coarser meshes at lower zoom; tighten the error budget as z grows. */
function meshMaxErrorForZoom(z: number): number {
  // 1000m at z=0, halving roughly per level, floored at 1m.
  return Math.max(1, 1000 / 2 ** z);
}

async function meshLayerJson(
  req: Request,
  tileset: Tileset,
  dataType: SampleDataType,
): Promise<Response> {
  return metadataJson(req, {
    tilejson: "2.1.0",
    format: "quantized-mesh-1.0",
    version: resolveTilesetVersion(tileset),
    name: `${tileset.name} / cesium-mesh / ${dataType}`,
    description: tileset.description,
    scheme: "tms",
    projection: "EPSG:4326",
    tiles: [`{z}/{x}/{y}.terrain`],
    minzoom: tileset.minZoom,
    maxzoom: tileset.maxZoom,
    bounds: [-180, -90, 180, 90],
    // Cesium may opt into the watermask extension at tile-fetch time, so
    // include the watermask source credits alongside the base attribution.
    attribution: [
      ...tileset.attribution,
      ...(tileset.watermask?.attribution ?? []),
    ]
      .map((a) => (a.url ? `<a href="${a.url}">${a.name}</a>` : a.name))
      .join(", "),
    // Advertise optional extensions; Cesium opts in via `requestVertexNormals`
    // / `requestWaterMask`, which appends `?extensions=...` to tile URLs.
    extensions: ["octvertexnormals", "watermask"],
    available: fullAvailability(tileset.minZoom, tileset.maxZoom),
  });
}

async function tilejson(
  req: Request,
  tileset: Tileset,
  encoding: Encoding,
  dataType: DataType,
): Promise<Response> {
  const base = new URL(req.url);
  base.pathname = `/${tileset.name}/${encoding}/${dataType}`;
  return metadataJson(req, {
    tilejson: "3.0.0",
    name: `${tileset.name} / ${encoding} / ${dataType}`,
    description: tileset.description,
    version: resolveTilesetVersion(tileset),
    scheme: "xyz",
    tiles: [`${base.toString()}/{z}/{x}/{y}.webp`],
    attribution: tileset.attribution
      .map((a) => (a.url ? `<a href="${a.url}">${a.name}</a>` : a.name))
      .join(", "),
    minzoom: tileset.minZoom,
    maxzoom: tileset.maxZoom,
    bounds: [-180, -85.0511287798066, 180, 85.0511287798066],
  });
}

function tilesetSummary(t: Tileset) {
  return {
    name: t.name,
    version: resolveTilesetVersion(t),
    description: t.description,
    attribution: t.attribution,
    minzoom: t.minZoom,
    maxzoom: t.maxZoom,
  };
}

async function debugCog(url: URL, env: Env): Promise<Response> {
  const key = url.searchParams.get("key");
  if (!key) return json({ error: "missing ?key=" }, { status: 400 });

  const { image } = await openCog(env.R2, key, { probeSize: true });
  return json({
    key,
    width: image.getWidth(),
    height: image.getHeight(),
    origin: image.getOrigin(),
    resolution: image.getResolution(),
    boundingBox: image.getBoundingBox(),
    samplesPerPixel: image.getSamplesPerPixel(),
    bytesPerPixel: image.getBytesPerPixel(),
    tileWidth: image.getTileWidth(),
    tileHeight: image.getTileHeight(),
  });
}

async function debugTile(url: URL, env: Env): Promise<Response> {
  const key = url.searchParams.get("key");
  const z = Number(url.searchParams.get("z") ?? "0");
  const x = Number(url.searchParams.get("x") ?? "0");
  const y = Number(url.searchParams.get("y") ?? "0");
  if (!key) return json({ error: "missing ?key=" }, { status: 400 });

  const { image } = await openCog(env.R2, key);
  const result = await readTileFromImage(image, z, x, y);

  return json({
    bounds: tileToLonLatBounds(z, x, y),
    window: result.window,
    outOfBounds: result.outOfBounds,
    outWidth: result.outWidth,
    outHeight: result.outHeight,
    samples: result.data.length,
    stats: summarize(result.data),
    first8: Array.from(result.data.slice(0, 8)),
  });
}

async function debugDem(url: URL): Promise<Response> {
  const tilesetName = url.searchParams.get("tileset");
  const tileset = resolveTileset(tilesetName ?? undefined);
  if (!tileset) return notFound(`unknown tileset: ${tilesetName}`);
  const z = Number(url.searchParams.get("z") ?? "10");
  const x = Number(url.searchParams.get("x") ?? "909");
  const y = Number(url.searchParams.get("y") ?? "403");

  const t0 = Date.now();
  const tile = await tileset.dem.read(z, x, y);
  const fetchMs = Date.now() - t0;
  if (!tile) return json({ tileset: tileset.name, dem: tileset.dem.name, z, x, y, hit: false });

  return json({
    tileset: tileset.name,
    dem: tileset.dem.name,
    z,
    x,
    y,
    width: tile.width,
    height: tile.height,
    bounds: tileToLonLatBounds(z, x, y),
    stats: summarize(tile.elevations),
    fetchMs,
  });
}

async function debugSamples(url: URL, env: Env): Promise<Response> {
  const tilesetName = url.searchParams.get("tileset");
  const tileset = resolveTileset(tilesetName ?? undefined);
  if (!tileset) return notFound(`unknown tileset: ${tilesetName}`);
  const dataType = (url.searchParams.get("type") ?? "ellipsoid") as DataType;
  const z = Number(url.searchParams.get("z") ?? "10");
  const x = Number(url.searchParams.get("x") ?? "909");
  const y = Number(url.searchParams.get("y") ?? "403");

  const t0 = Date.now();
  const samples = await readTileSamples(tileset, dataType, z, x, y, env);
  const blendMs = Date.now() - t0;
  return json({
    tileset: tileset.name,
    dataType,
    z,
    x,
    y,
    width: samples.width,
    height: samples.height,
    bounds: tileToLonLatBounds(z, x, y),
    stats: summarize(samples.values),
    blendMs,
  });
}

async function debugWaterMask(url: URL, env: Env): Promise<Response> {
  const z = Number(url.searchParams.get("z") ?? "10");
  const x = Number(url.searchParams.get("x") ?? "1051");
  const y = Number(url.searchParams.get("y") ?? "809");
  const tilesetName = url.searchParams.get("tileset");
  const tileset = resolveTileset(tilesetName ?? undefined);
  if (!tileset) return notFound(`unknown tileset: ${tilesetName}`);
  const bounds = geodeticTileBounds(z, x, y);
  const wm = await resolveWatermask(tileset);
  if (!wm) return json({ error: "watermask disabled for tileset", tileset: tileset.name });

  const t0 = Date.now();
  const mask = await wm.provider.buildMask(bounds);
  const ms = Date.now() - t0;

  let waterCells = 0;
  let landCells = 0;
  let kind: "uniform-land" | "uniform-water" | "grid" = "grid";
  if (mask.length === 1) {
    kind = mask[0] === 255 ? "uniform-water" : "uniform-land";
  } else {
    for (const v of mask) {
      if (v === 255) waterCells++;
      else landCells++;
    }
  }
  return json({
    z, x, y, bounds, ms,
    source: { url: wm.url, version: wm.version },
    kind,
    maskBytes: mask.length,
    ...(kind === "grid"
      ? { waterCells, landCells, waterFraction: waterCells / (waterCells + landCells) }
      : {}),
  });
}

/**
 * Snapshot every live tileset's currently-resolved version into the
 * `CleanupTileset` shape the sweep expects. Keeps the cron path and the
 * debug endpoint pointing at the same versions and centralizes the
 * `Tileset → CleanupTileset` projection.
 */
function resolveLiveCleanupTilesets(): Record<string, { name: string; version: string }> {
  const out: Record<string, { name: string; version: string }> = {};
  for (const [key, t] of Object.entries(TILESETS)) {
    out[key] = { name: t.name, version: resolveTilesetVersion(t) };
  }
  return out;
}

async function debugCleanup(url: URL, env: Env): Promise<Response> {
  if (!env.R2) return json({ error: "R2 binding missing" }, { status: 500 });
  const dryRun = url.searchParams.get("dryRun") !== "0";
  const maxDeletes = Number(url.searchParams.get("maxDeletes") ?? "5000");
  const t0 = Date.now();
  const result = await runCleanup(env.R2, resolveLiveCleanupTilesets(), { dryRun, maxDeletes });
  return json({ ...result, ms: Date.now() - t0 });
}

function summarize(arr: Float32Array): { min: number; max: number; mean: number; valid: number } | null {
  let min = Infinity;
  let max = -Infinity;
  let sum = 0;
  let n = 0;
  for (const v of arr) {
    if (!Number.isFinite(v) || v <= -9999) continue;
    if (v < min) min = v;
    if (v > max) max = v;
    sum += v;
    n++;
  }
  return n > 0 ? { min, max, mean: sum / n, valid: n } : null;
}

function json(body: unknown, init?: ResponseInit): Response {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: {
      "content-type": "application/json; charset=utf-8",
      ...(init?.headers ?? {}),
    },
  });
}

const METADATA_CACHE_CONTROL = "public, max-age=3600";

/** JSON response with strong ETag + If-None-Match support. */
async function metadataJson(req: Request, body: unknown): Promise<Response> {
  const text = JSON.stringify(body);
  const etag = await bodyEtag(text);
  if (matchesIfNoneMatch(req.headers.get("if-none-match"), etag)) {
    return new Response(null, {
      status: 304,
      headers: { etag, "cache-control": METADATA_CACHE_CONTROL },
    });
  }
  return new Response(text, {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": METADATA_CACHE_CONTROL,
      etag,
    },
  });
}

function notFound(message = "Not Found"): Response {
  return new Response(message, { status: 404 });
}
